### ISSUE TITLE
why do you use the pub/sub at all?

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [Giriskenisa/coinHaven#4]
https://github.com/Giriskenisa/coinHaven/blob/120a4f374aa405b4918f30782831e5d5664ee65f/src/lib/user-register.js#L19

**Comment by Giriskenisa** [comment]
Hello Dimitry,
Im sorry 😞 but still don’t know what the task wants from me this is what ı understand. I couldnt setup the logic. This is what ı understand.
Is this structure You want ? 
![AD34C08E-9521-45F9-9544-9C4D5E1D72CD](https://user-images.githubusercontent.com/42315941/130316716-fa0db5a8-d74c-4719-bd95-7ddf18456394.jpeg)

**Comment by Dmitry-N-Medvedev** [comment]
no pub/sub is expected for this task.
